/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },

    // {
    //   type: 'category',
    //   label: 'API Reference',
    //   link: {
    //     type: 'generated-index',
    //     title: 'API Reference',
    //     description: 'Overview of available OpenTDF APIs.',
    //     slug: '/category/api-reference', // This will create an index page at /category/api-reference
    //   },
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'KAS API',
    //       link: {
    //         type: 'generated-index',
    //         title: 'KAS API Overview',
    //         slug: '/api/kas', // This should be the base path for KAS API docs
    //       },
    //       // @ts-ignore - Docusaurus type system might complain about require in JS
    //       items: require('./docs/api/kas/sidebar.js'), // Path to the sidebar generated by docusaurus-plugin-openapi-docs
    //       // items: require('./sidebar.js'), // Path to the sidebar generated by docusaurus-plugin-openapi-docs
    //     },
  ],
};

export default sidebars;
