name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  vale-check:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          filter_mode: added
          vale_flags: "--glob=!blog/* --config=.vale.ini"
          debug: true
      # - name: find files
      #   if: always()
      #   run: tree -f  / | grep RedHat
      - name: list styles
        if: always()
        run: ls .github/vale-styles